# Generated by Django 3.0.7 on 2020-07-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200708_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetter',
            new_name='NewsLetterSubscriber',
        ),
    ]
