# Generated by Django 3.0.7 on 2020-07-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200708_1821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsPost',
        ),
    ]
